ipfs/blog

- src/13-ipfs-weekly-8/index.md
- versions/current
- versions/history
```
ipfs swarm peers >/dev/null || (echo "ipfs daemon must be online to publish" && exit 1)
ipfs add -r -q build/ | tail -n1 >versions/current
cat versions/current >>versions/history
published blog:
- http://localhost:8080/ipfs/QmRCheYarSTnqDRxkvpR7DMXWkmzJV4ZFyrLLpqudcSb7J
- https://ipfs.io/ipfs/QmRCheYarSTnqDRxkvpR7DMXWkmzJV4ZFyrLLpqudcSb7J
next steps:
- ipfs pin add -r /ipfs/QmRCheYarSTnqDRxkvpR7DMXWkmzJV4ZFyrLLpqudcSb7J
- make publish-to-domain
```
> Added IPFS Weekly 8

- src/18-v03x-shutdown/index.md
Title: go-ipfs 0.3.x network shutdown on July 14th
Preview: https://ipfs.io/ipfs/QmV7mkPEHLL8m4LkyR759oRgFfMQwmDAZCUzGisWjQzpY3/18-v03x-shutdown/
> post: v03x network shutdown

- src/21-go-ipfs-0-4-4-released/index.md
The "bug" and "find out if you're affected" sections still need a bit of wording polish.
cc @jbenet @whyrusleeping @RichardLitt
> go-ipfs 0.4.4 has been released

- src/23-js-ipfs-0-23/index.md
Time to kick up the blog again. Very simple post describing the latest js-ipfs release.
> Add blogpost for js-ipfs release 0.23.0

- tmpl/layouts/basic.html
I agree with @lgierth's suggestion that we should make GA only load when you're viewing the content through ipfs.io gateway but in the meantime I think we need these metrics.
This is a straight copy from https://github.com/ipfs/website/blob/534c4cee29f41ff49cfbcc1196bf45cde6eb6809/ipfs.io-theme/templates/base.html#L132-L139
I'm _pretty sure_ it will work as-is but someone should double-check.
> add google analytics

- config.toml
- layouts/index.json
This allows the homepage to GET and display the latest blog posts without having to parse XML.
> Adds a posts JSON for consumption by the IPFS homepage

- config.toml
- content/index.html
- layouts/partials/footer.html
- layouts/partials/head.html
* Adds OG and Twitter meta tags in line with the other sites.
* Uses built-in Hugo template to render async GA code in the header.
> Update head meta tags and GA code

- layouts/index.json
The `index.json` template now suppresses the comma after the item which is either the final post or the fourth, whichever comes first.
> Don't add trailing comma to JSON

- content/post/29-js-ipfs-pubsub.md
Example modified to clarify that waiting for 'ready' callback is.
> Add 'ready' callback to pubsub example

- content/post/30-js-ipfs-crdts.md
This was changed in https://github.com/ipfs/blog/pull/134/files#diff-e52d0fb3ee34fa19c0d281c14b1229ef as I noticed that hugo generates a file `public/30-js-ipfs-crdts.md` with HTML content when you suffix the URL with `.md` instead of the usual `public/30-js-ipfs-crdts/index.html`. I thought this wasn't resolving at all so the change was intended to fix this, which it did, but it _was_ actually resolving and I ended up breaking links to the content. It should never have been part of the re-style changeset so please accept my apologies for the error.
fixes #140
> Revert change to URL

- content/post/34-go-ipfs-0.4.14.md
Draft for announcing go-ipfs 0.4.14. Basically a copy-paste from the changelog but added some links and changed most "IPFS" mentions to "go-ipfs" to make it clearer for everyone reading the blog (also wrapped the lines, because otherwise the md file looks ugly)
> Announce go-ipfs 0.4.14

- content/post/22-run-ipfs-on-a-vps.md
The tar ball's directory name was updated from `ipfs` to `go-ipfs`.
Also, I updated same lines.
P.S. I could install and work IPFS on [vultr](https://www.vultr.com/). Thanks 😃
> Fix wrong tar ball's directory name

- content/post/38-js-ipfs-0.29.md
Anyone available to do a proof read?
> js-ipfs 0.29.0 release blog post

- layouts/partials/footer.html
- layouts/partials/header.html
Our new official docs site, with much more info, is now at https://docs.ipfs.io instead of the `/docs` directory that is part of this site. This PR updates the header and footer here in the blog to match the changes we recently made to the website (ipfs/website#266) by pointing all the docs-related URLs to docs.ipfs.io instead of ipfs.io/docs.
> Change all docs links to new site (docs.ipfs.io)

- config.toml
- layouts/partials/head.html
> Context: https://github.com/ipfs/website/issues/274#issuecomment-427210000 + https://github.com/ipfs/website/pull/275
This PR changes default URL used in permalinks in https://blog.ipfs.io/index.json and https://blog.ipfs.io/index.xml from `https://ipfs.io/blog/` to `https://blog.ipfs.io`. 
Small change but makes:
-   blog permalinks  work when loaded via IPNS
-   `blog.ipfs.io/index.json` and RSS feed useful on `ipfs.io` even when loaded over IPNS, solving errors like the one below:
>  ![2018-10-05--01-32-46](https://user-images.githubusercontent.com/157609/46509585-e67b3b80-c843-11e8-91a7-94dbd82d2c3d.png)
It should be safe to do this, as those are used only in:
-  RSS and JSON outputs
- `meta` headers for Facebook embeds
Closes #145
> fix: blog permalinks that work on IPNS

- content/post/0-hello-worlds.md
- layouts/partials/head.html
- layouts/rss.xml
Closes #188 
- Adds full text (HTML) version of posts
- There is also a short summary for readers that support both in different views
- Full text feed grew to .5MB so I limited it to 10 latest entries, it is ~70K now
- Added missing (fav)icons
- Fixed broken links in first post
@diasdavid  are you able to smoke-test [this static snapshot](https://ipfs.io/ipfs/QmX77F8MLrqtVEaoUmZsDdMpUP6W4FJJUyKQxN7m3Gean1/index.xml) in your reader?
> Include full text in RSS/Atom feed

- content/post/80-js-ipfs-0.35.md
> post: add js-ipfs 0.35 release post

- content/post/81-js-libp2p-0.25.md
Libp2p 0.25 is out! Let's 🌮 about it.
> post: add js-libp2p 0.25 release post

- layouts/partials/header.html
Fixes the broken [installation link](https://docs.ipfs.io/introduction/install/) which currently renders the following.
> Fix installation link

- README.md
I think the pipeline doc is also out of date, but I am not familiar enough with the new mechanical workings to update it correctly. I believe we now use Travis instead of circle? And you no longer need to redeploy the website to publish new  posts?
> Add note about publish date

- content/post/050-ipfs-camp-recap.md
I added this as a comment on the original PR but I think I did it just after it was merged..
Small typo: "laser" stands for "Light Amplification by Stimulated Emission of Radiation" so is never spelt with a "z"
> docs: fix typo

- README.md
Old "Want to hack on IPFS?" link 404'd cause CONTRIBUTING.md was written in all lowers. It's fixed now.
> Contributing link case-sensitivity fix

- README.md
Clarify in the readme that setting a post's date for the future will cause it to not be displayed and prevent previewing your work.
> Explain that postdated posts can't be previewed

- README.md
- config.toml
- layouts/partials/footer.html
- layouts/partials/header.html
Updates header and footer to consistency with https://github.com/ipfs/website/pull/348
- Footer was out of date for a while, this removes Google Plus link and adds ProtoSchool and related projects menus
- Header now matches rest of website's header (or at least once website/pull/348 is merged); combines "implementations" and "install" items into one easier-to-use area of guidance on main website
This completes the work laid out under issue https://github.com/ipfs/website/issues/293
> Updates header and footer

- content-i18n/zh-cn/post/weekly-63.md
- content-i18n/zh-cn/post/weekly-69.md
- content-i18n/zh-cn/post/weekly-70.md
This PR fixes english version of IPFS Weekly 63, 69 and 70
Context: some URLs of Chinese versions of blogposts were not prefixed  by `zh-cn/` which made it impossible to load English versions (both links opened Chinese). 
@moyid @renrutnnej  for future reference, make sure translated version has URL prefixed with language code:
```diff
---
date: 2019-12-03
- url: weekly-70
+ url: zh-cn/weekly-70
```
> fix: zh-cn links for IPFS Weekly

- .circleci/config.yml
Hugo allows posts to be published in the future, and they will only appear when that date arrives. Adding a nightly build allows us to use that feature...
See: https://circleci.com/docs/2.0/configuration-reference/#triggers
Fixes #365
License: MIT
> feat: add a nightly ci build

- content/post/081-js-libp2p-0.27.md
For the libp2p 0.27 release, https://github.com/libp2p/js-libp2p/issues/487.
>  post: release of js-libp2p 0.27

- content/post/083-js-ipfs-0.41.md
It shipped, why wait till tomorrow?
> chore: publish js-ipfs 0.41 post

- layouts/partials/head.html
- static/js/main.js
This closes https://github.com/ipfs/blog/issues/360 by detecting page loads from `ipfs.io/blog` and replacing them with `blog.ipfs.io`.
This ensures canonical link is always present when loaded via DNSLink.
Remaining fix will land in ipfs-companion.
> fix: redirect to canonical link when loaded from ipfs.io/blog

- layouts/post/single.html
This PR implements the idea from https://github.com/ipfs/blog/issues/360#issuecomment-585851942
Idea is simple:
Discussion threads created at discuss.ipfs.io for blog posts with dates after 2020-03-01 would use `blog.ipfs.io` instead of `ipfs.io/blog`. 
This would close  #360 
cc @olizilla  for sanity check ;-)
> fix: use blog.ipfs.io in new posts at discuss.ipfs.io

- content/post/019-js-ipfs-crdts.md
- content/post/026-ipfs-conf-dev-meetings-and-user-registry.md
I checked and these seem the only two `.md$` urls.
> Fix #313: fix urls

- content/post/085-announcing-rust-ipfs.md
Submitting a rough draft of the Rust IPFS blog post. I put an index of 085 on it and a date of March 16 to post. What I'd like to do, pending approval here, is afterward write the longer, more technical and in-depth post on the Equilibrium Blog. We can launch them together and cross-link.
@vmx and whomever else are welcome to share the byline there as well.
cc @momack2 for review
> Create Rust IPFS Blog Post

- layouts/partials/footer.html
- layouts/partials/header.html
To bring into line with @hsanjuan's addition of expanded help page to the main ipfs.io. (Changes to the blog header/footer need to be made separately to the main site.)
> Forum -> Help in header and footer

- content/post/094-js-ipfs-0.44.md
- content/post/096-js-ipfs-0.44.md
Adds a post for the latest js-ipfs release, published earlier today.
> docs: add blog post for js-ipfs 0.44.0

- layouts/post/single.html
This should prevent a leading/trailing and/or duplicate slashes from generating different discourse threads.
> fix: clean URLs in the discourse integration

- content/post/101-go-ipfs-0-6-0.md
This is a trimmed down, cleaned up version of the release notes. As we aim to release more often, the goal is to improve the pipeline from release notes to blog post. I'd like to have high level summaries here that give you enough info about what each feature/fix contains, with links to their more technical counterparts in the release notes /readmes.
> docs: add blog post for go-ipfs 0.6

- .circleci/config.yml
- .gitignore
- package-lock.json
a dep started breaking the build with errors of the form
```
npm ERR! Invalid dependency type requested: alias
```
which it turns out is a feature only supported in npm >= 6.9.
So this PR updeates the docker image and pins the deps by including the package-lock.json.
If you have a local package-lock.json, delete it, and accept this one into your heart.
License: MIT
> chore: fix ci. pin deps

- content/post/106-ipfs-meetup-aug2020.md
Fixes video embeds.
License: MIT
> fix: video embed urls

- content/post/125-go-ipfs-0-8-0.md
URI typo fix:
`https://blog.ipfs.io/2021-02-19-go-ipfs-0-6-0/` will alias over to `https://blog.ipfs.io/2021-02-19-go-ipfs-0-8-0/`
> Add URI alias for 0.8 release post
